// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerCop.proto

package com;

import java.io.IOException;

public final class ServerCop {
  private ServerCop() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RowCountRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 starttime = 2;
    /**
     * <code>required int64 starttime = 2;</code>
     */
    boolean hasStarttime();
    /**
     * <code>required int64 starttime = 2;</code>
     */
    long getStarttime();

    // required int64 endtime = 1;
    /**
     * <code>required int64 endtime = 1;</code>
     */
    boolean hasEndtime();
    /**
     * <code>required int64 endtime = 1;</code>
     */
    long getEndtime();
  }
  /**
   * Protobuf type {@code RowCountRequest}
   */
  public static final class RowCountRequest extends
      com.google.protobuf.GeneratedMessage
      implements RowCountRequestOrBuilder {
    // Use RowCountRequest.newBuilder() to construct.
    private RowCountRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RowCountRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RowCountRequest defaultInstance;
    public static RowCountRequest getDefaultInstance() {
      return defaultInstance;
    }

    public RowCountRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RowCountRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000002;
              endtime_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              starttime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ServerCop.internal_static_RowCountRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ServerCop.internal_static_RowCountRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ServerCop.RowCountRequest.class, com.ServerCop.RowCountRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<RowCountRequest> PARSER =
        new com.google.protobuf.AbstractParser<RowCountRequest>() {
      public RowCountRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RowCountRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RowCountRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 starttime = 2;
    public static final int STARTTIME_FIELD_NUMBER = 2;
    private long starttime_;
    /**
     * <code>required int64 starttime = 2;</code>
     */
    public boolean hasStarttime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 starttime = 2;</code>
     */
    public long getStarttime() {
      return starttime_;
    }

    // required int64 endtime = 1;
    public static final int ENDTIME_FIELD_NUMBER = 1;
    private long endtime_;
    /**
     * <code>required int64 endtime = 1;</code>
     */
    public boolean hasEndtime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 endtime = 1;</code>
     */
    public long getEndtime() {
      return endtime_;
    }

    private void initFields() {
      starttime_ = 0L;
      endtime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStarttime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndtime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(1, endtime_);
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(2, starttime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, endtime_);
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, starttime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ServerCop.RowCountRequest)) {
        return super.equals(obj);
      }
      com.ServerCop.RowCountRequest other = (com.ServerCop.RowCountRequest) obj;

      boolean result = true;
      result = result && (hasStarttime() == other.hasStarttime());
      if (hasStarttime()) {
        result = result && (getStarttime()
            == other.getStarttime());
      }
      result = result && (hasEndtime() == other.hasEndtime());
      if (hasEndtime()) {
        result = result && (getEndtime()
            == other.getEndtime());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasStarttime()) {
        hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getStarttime());
      }
      if (hasEndtime()) {
        hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getEndtime());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ServerCop.RowCountRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ServerCop.RowCountRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ServerCop.RowCountRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ServerCop.RowCountRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ServerCop.RowCountRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ServerCop.RowCountRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ServerCop.RowCountRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ServerCop.RowCountRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ServerCop.RowCountRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ServerCop.RowCountRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ServerCop.RowCountRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RowCountRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ServerCop.RowCountRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ServerCop.internal_static_RowCountRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ServerCop.internal_static_RowCountRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ServerCop.RowCountRequest.class, com.ServerCop.RowCountRequest.Builder.class);
      }

      // Construct using com.ServerCop.RowCountRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        starttime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        endtime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ServerCop.internal_static_RowCountRequest_descriptor;
      }

      public com.ServerCop.RowCountRequest getDefaultInstanceForType() {
        return com.ServerCop.RowCountRequest.getDefaultInstance();
      }

      public com.ServerCop.RowCountRequest build() {
        com.ServerCop.RowCountRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ServerCop.RowCountRequest buildPartial() {
        com.ServerCop.RowCountRequest result = new com.ServerCop.RowCountRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.starttime_ = starttime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.endtime_ = endtime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ServerCop.RowCountRequest) {
          return mergeFrom((com.ServerCop.RowCountRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ServerCop.RowCountRequest other) {
        if (other == com.ServerCop.RowCountRequest.getDefaultInstance()) return this;
        if (other.hasStarttime()) {
          setStarttime(other.getStarttime());
        }
        if (other.hasEndtime()) {
          setEndtime(other.getEndtime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStarttime()) {
          
          return false;
        }
        if (!hasEndtime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ServerCop.RowCountRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ServerCop.RowCountRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 starttime = 2;
      private long starttime_ ;
      /**
       * <code>required int64 starttime = 2;</code>
       */
      public boolean hasStarttime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 starttime = 2;</code>
       */
      public long getStarttime() {
        return starttime_;
      }
      /**
       * <code>required int64 starttime = 2;</code>
       */
      public Builder setStarttime(long value) {
        bitField0_ |= 0x00000001;
        starttime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 starttime = 2;</code>
       */
      public Builder clearStarttime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        starttime_ = 0L;
        onChanged();
        return this;
      }

      // required int64 endtime = 1;
      private long endtime_ ;
      /**
       * <code>required int64 endtime = 1;</code>
       */
      public boolean hasEndtime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 endtime = 1;</code>
       */
      public long getEndtime() {
        return endtime_;
      }
      /**
       * <code>required int64 endtime = 1;</code>
       */
      public Builder setEndtime(long value) {
        bitField0_ |= 0x00000002;
        endtime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 endtime = 1;</code>
       */
      public Builder clearEndtime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        endtime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RowCountRequest)
    }

    static {
      defaultInstance = new RowCountRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RowCountRequest)
  }

  public interface RowCountResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 rownum = 1;
    /**
     * <code>required int64 rownum = 1;</code>
     */
    boolean hasRownum();
    /**
     * <code>required int64 rownum = 1;</code>
     */
    long getRownum();
  }
  /**
   * Protobuf type {@code RowCountResponse}
   */
  public static final class RowCountResponse extends
      com.google.protobuf.GeneratedMessage
      implements RowCountResponseOrBuilder {
    // Use RowCountResponse.newBuilder() to construct.
    private RowCountResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RowCountResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RowCountResponse defaultInstance;
    public static RowCountResponse getDefaultInstance() {
      return defaultInstance;
    }

    public RowCountResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RowCountResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rownum_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ServerCop.internal_static_RowCountResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ServerCop.internal_static_RowCountResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ServerCop.RowCountResponse.class, com.ServerCop.RowCountResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<RowCountResponse> PARSER =
        new com.google.protobuf.AbstractParser<RowCountResponse>() {
      public RowCountResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RowCountResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RowCountResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 rownum = 1;
    public static final int ROWNUM_FIELD_NUMBER = 1;
    private long rownum_;
    /**
     * <code>required int64 rownum = 1;</code>
     */
    public boolean hasRownum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 rownum = 1;</code>
     */
    public long getRownum() {
      return rownum_;
    }

    private void initFields() {
      rownum_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRownum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, rownum_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, rownum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ServerCop.RowCountResponse)) {
        return super.equals(obj);
      }
      com.ServerCop.RowCountResponse other = (com.ServerCop.RowCountResponse) obj;

      boolean result = true;
      result = result && (hasRownum() == other.hasRownum());
      if (hasRownum()) {
        result = result && (getRownum()
            == other.getRownum());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRownum()) {
        hash = (37 * hash) + ROWNUM_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getRownum());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ServerCop.RowCountResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ServerCop.RowCountResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ServerCop.RowCountResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ServerCop.RowCountResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ServerCop.RowCountResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ServerCop.RowCountResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ServerCop.RowCountResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ServerCop.RowCountResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ServerCop.RowCountResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ServerCop.RowCountResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ServerCop.RowCountResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RowCountResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ServerCop.RowCountResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ServerCop.internal_static_RowCountResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ServerCop.internal_static_RowCountResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ServerCop.RowCountResponse.class, com.ServerCop.RowCountResponse.Builder.class);
      }

      // Construct using com.ServerCop.RowCountResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rownum_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ServerCop.internal_static_RowCountResponse_descriptor;
      }

      public com.ServerCop.RowCountResponse getDefaultInstanceForType() {
        return com.ServerCop.RowCountResponse.getDefaultInstance();
      }

      public com.ServerCop.RowCountResponse build() {
        com.ServerCop.RowCountResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ServerCop.RowCountResponse buildPartial() {
        com.ServerCop.RowCountResponse result = new com.ServerCop.RowCountResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rownum_ = rownum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ServerCop.RowCountResponse) {
          return mergeFrom((com.ServerCop.RowCountResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ServerCop.RowCountResponse other) {
        if (other == com.ServerCop.RowCountResponse.getDefaultInstance()) return this;
        if (other.hasRownum()) {
          setRownum(other.getRownum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRownum()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ServerCop.RowCountResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ServerCop.RowCountResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 rownum = 1;
      private long rownum_ ;
      /**
       * <code>required int64 rownum = 1;</code>
       */
      public boolean hasRownum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 rownum = 1;</code>
       */
      public long getRownum() {
        return rownum_;
      }
      /**
       * <code>required int64 rownum = 1;</code>
       */
      public Builder setRownum(long value) {
        bitField0_ |= 0x00000001;
        rownum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 rownum = 1;</code>
       */
      public Builder clearRownum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rownum_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RowCountResponse)
    }

    static {
      defaultInstance = new RowCountResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RowCountResponse)
  }

  /**
   * Protobuf service {@code CopCountService}
   */
  public static abstract class CopCountService
      implements com.google.protobuf.Service {
    protected CopCountService() {}

    public interface Interface {
      /**
       * <code>rpc getCount(.RowCountRequest) returns (.RowCountResponse);</code>
       */
      public abstract void getCount(
          com.google.protobuf.RpcController controller,
          com.ServerCop.RowCountRequest request,
          com.google.protobuf.RpcCallback<com.ServerCop.RowCountResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new CopCountService() {
        @java.lang.Override
        public  void getCount(
            com.google.protobuf.RpcController controller,
            com.ServerCop.RowCountRequest request,
            com.google.protobuf.RpcCallback<com.ServerCop.RowCountResponse> done) {
          impl.getCount(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getCount(controller, (com.ServerCop.RowCountRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.ServerCop.RowCountRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.ServerCop.RowCountResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getCount(.RowCountRequest) returns (.RowCountResponse);</code>
     * @throws IOException 
     */
    public abstract void getCount(
        com.google.protobuf.RpcController controller,
        com.ServerCop.RowCountRequest request,
        com.google.protobuf.RpcCallback<com.ServerCop.RowCountResponse> done) throws IOException;

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.ServerCop.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          try {
			this.getCount(controller, (com.ServerCop.RowCountRequest)request,
			    com.google.protobuf.RpcUtil.<com.ServerCop.RowCountResponse>specializeCallback(
			      done));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.ServerCop.RowCountRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.ServerCop.RowCountResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.ServerCop.CopCountService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getCount(
          com.google.protobuf.RpcController controller,
          com.ServerCop.RowCountRequest request,
          com.google.protobuf.RpcCallback<com.ServerCop.RowCountResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.ServerCop.RowCountResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.ServerCop.RowCountResponse.class,
            com.ServerCop.RowCountResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.ServerCop.RowCountResponse getCount(
          com.google.protobuf.RpcController controller,
          com.ServerCop.RowCountRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.ServerCop.RowCountResponse getCount(
          com.google.protobuf.RpcController controller,
          com.ServerCop.RowCountRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.ServerCop.RowCountResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.ServerCop.RowCountResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:CopCountService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RowCountRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RowCountRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RowCountResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RowCountResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ServerCop.proto\"5\n\017RowCountRequest\022\021\n\t" +
      "starttime\030\002 \002(\003\022\017\n\007endtime\030\001 \002(\003\"\"\n\020RowC" +
      "ountResponse\022\016\n\006rownum\030\001 \002(\0032B\n\017CopCount" +
      "Service\022/\n\010getCount\022\020.RowCountRequest\032\021." +
      "RowCountResponseB\030\n\003comB\tServerCopH\001\210\001\001\240" +
      "\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RowCountRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RowCountRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RowCountRequest_descriptor,
              new java.lang.String[] { "Starttime", "Endtime", });
          internal_static_RowCountResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_RowCountResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RowCountResponse_descriptor,
              new java.lang.String[] { "Rownum", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
